ruby '2.1.5'
source 'https://rubygems.org'

gem 'faraday'
gem 'faraday_middleware'
gem 'haml'
gem 'json'
gem 'octokit'
gem 'puma'
gem 'rack'
gem 'rack-test'
gem 'rake'
gem 'rspec'
gem 'rspec-mocks'
gem 'parseconfig'
gem 'shotgun'
gem 'sinatra'
gem 'sinatra-contrib'
