GITHUB_POSTBODY_RELEASE = '{
  "ref": "refs/tags/v3.0.0",
  "before": "0000000000000000000000000000000000000000",
  "after": "a779a46381d0d10c8e9dc390da0eaf567465cb39",
  "created": true,
  "deleted": false,
  "forced": true,
  "base_ref": "refs/heads/master",
  "compare": "https://github.com/matthewjackowski/txgh-test-resources/compare/v3.0.0",
  "commits": [

  ],
  "head_commit": {
    "id": "a779a46381d0d10c8e9dc390da0eaf567465cb39",
    "distinct": true,
    "message": "11",
    "timestamp": "2015-11-18T16:18:35-08:00",
    "url": "https://github.com/matthewjackowski/txgh-test-resources/commit/a779a46381d0d10c8e9dc390da0eaf567465cb39",
    "author": {
      "name": "Matthew Jackowski",
      "email": "mattjjacko@gmail.com",
      "username": "matthewjackowski"
    },
    "committer": {
      "name": "Matthew Jackowski",
      "email": "mattjjacko@gmail.com",
      "username": "matthewjackowski"
    },
    "added": [

    ],
    "removed": [

    ],
    "modified": [
      "sample.po"
    ]
  },
  "repository": {
    "id": 41740726,
    "name": "txgh-test-resources",
    "full_name": "matthewjackowski/txgh-test-resources",
    "owner": {
      "name": "matthewjackowski",
      "email": "mattjjacko@gmail.com"
    },
    "private": false,
    "html_url": "https://github.com/matthewjackowski/txgh-test-resources",
    "description": "Translation test repo for txgh",
    "fork": false,
    "url": "https://github.com/matthewjackowski/txgh-test-resources",
    "forks_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/forks",
    "keys_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/teams",
    "hooks_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/hooks",
    "issue_events_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/issues/events{/number}",
    "events_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/events",
    "assignees_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/assignees{/user}",
    "branches_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/branches{/branch}",
    "tags_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/tags",
    "blobs_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/languages",
    "stargazers_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/stargazers",
    "contributors_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/contributors",
    "subscribers_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/subscribers",
    "subscription_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/subscription",
    "commits_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/contents/{+path}",
    "compare_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/merges",
    "archive_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/downloads",
    "issues_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/issues{/number}",
    "pulls_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/labels{/name}",
    "releases_url": "https://api.github.com/repos/matthewjackowski/txgh-test-resources/releases{/id}",
    "created_at": 1441114620,
    "updated_at": "2015-09-01T13:37:00Z",
    "pushed_at": 1447892352,
    "git_url": "git://github.com/matthewjackowski/txgh-test-resources.git",
    "ssh_url": "git@github.com:matthewjackowski/txgh-test-resources.git",
    "clone_url": "https://github.com/matthewjackowski/txgh-test-resources.git",
    "svn_url": "https://github.com/matthewjackowski/txgh-test-resources",
    "homepage": null,
    "size": 11,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master",
    "stargazers": 0,
    "master_branch": "master"
  },
  "pusher": {
    "name": "matthewjackowski",
    "email": "mattjjacko@gmail.com"
  },
  "sender": {
    "login": "matthewjackowski",
    "id": 974299,
    "avatar_url": "https://avatars.githubusercontent.com/u/974299?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/matthewjackowski",
    "html_url": "https://github.com/matthewjackowski",
    "followers_url": "https://api.github.com/users/matthewjackowski/followers",
    "following_url": "https://api.github.com/users/matthewjackowski/following{/other_user}",
    "gists_url": "https://api.github.com/users/matthewjackowski/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/matthewjackowski/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/matthewjackowski/subscriptions",
    "organizations_url": "https://api.github.com/users/matthewjackowski/orgs",
    "repos_url": "https://api.github.com/users/matthewjackowski/repos",
    "events_url": "https://api.github.com/users/matthewjackowski/events{/privacy}",
    "received_events_url": "https://api.github.com/users/matthewjackowski/received_events",
    "type": "User",
    "site_admin": false
  }
}'