source 'https://rubygems.org'

gemspec

# @TODO: remove
gem 'txgh', path: '../txgh'

group :development, :test do
  gem 'pry-byebug'
  gem 'rake'
end

group :test do
  gem 'rack-test'
  gem 'rspec'
  gem 'vcr', '~> 3.0'
  gem 'webmock', '~> 1.0'
end
