module Txgh
  autoload :Application,          'txgh/app'
  autoload :Config,               'txgh/config'
  autoload :GithubApi,            'txgh/github_api'
  autoload :GithubRepo,           'txgh/github_repo'
  autoload :GithubRequestAuth,    'txgh/github_request_auth'
  autoload :Handlers,             'txgh/handlers'
  autoload :Hooks,                'txgh/app'
  autoload :KeyManager,           'txgh/key_manager'
  autoload :ParseConfig,          'txgh/parse_config'
  autoload :TransifexApi,         'txgh/transifex_api'
  autoload :TransifexProject,     'txgh/transifex_project'
  autoload :TransifexRequestAuth, 'txgh/transifex_request_auth'
  autoload :TxConfig,             'txgh/tx_config'
  autoload :TxLogger,             'txgh/tx_logger'
  autoload :TxResource,           'txgh/tx_resource'
end
