require 'txgh/errors'

module Txgh
  autoload :Application,          'txgh/app'
  autoload :CategorySupport,      'txgh/category_support'
  autoload :Config,               'txgh/config'
  autoload :GithubApi,            'txgh/github_api'
  autoload :GithubRepo,           'txgh/github_repo'
  autoload :GithubRequestAuth,    'txgh/github_request_auth'
  autoload :Handlers,             'txgh/handlers'
  autoload :Hooks,                'txgh/app'
  autoload :KeyManager,           'txgh/key_manager'
  autoload :ParseConfig,          'txgh/parse_config'
  autoload :ResourceCommitter,    'txgh/resource_committer'
  autoload :ResourceUpdater,      'txgh/resource_updater'
  autoload :TransifexApi,         'txgh/transifex_api'
  autoload :TransifexProject,     'txgh/transifex_project'
  autoload :TxBranchResource,     'txgh/tx_branch_resource'
  autoload :TransifexRequestAuth, 'txgh/transifex_request_auth'
  autoload :Triggers,             'txgh/app'
  autoload :TxBranchResource,     'txgh/tx_branch_resource'
  autoload :TxConfig,             'txgh/tx_config'
  autoload :TxLogger,             'txgh/tx_logger'
  autoload :TxResource,           'txgh/tx_resource'
  autoload :Utils,                'txgh/utils'
end
