source 'https://rubygems.org'

gemspec

gem 'txgh', path: '../txgh'
gem 'txgh-server', path: '../server'

group :development, :test do
  gem 'pry-byebug'
  gem 'rake'
end

group :test do
  gem 'rack-test'
  gem 'rspec'
end
